name: go-postgres

services:
  postgres:
    image: postgres:latest
    container_name: go-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/Postgres/go-home:/var/lib/postgresql/data
      # - ${HOME}/Postgres/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     - pg-network

networks:
  pg-network:
    name: pg-netowrk
